version: "3.8"
  
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: "${KEYCLOAK_DB_USER}"
      POSTGRES_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-network
  keycloak:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:${POSTGRES_PORT}/keycloak"
      KC_DB_USERNAME: "${KEYCLOAK_DB_USER}"
      KC_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      JGROUPS_DISCOVERY_EXTERNAL_IP: keycloak
    volumes:
      - ./config/realms:/opt/keycloak/data/import
    command: 
      - "start-dev"
      - "--import-realm"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - auth-network
  keycloak-2:
    depends_on:
      - keycloak
    build: .
    container_name: keycloak-2
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:${POSTGRES_PORT}/keycloak"
      KC_DB_USERNAME: "${KEYCLOAK_DB_USER}"
      KC_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      JGROUPS_DISCOVERY_EXTERNAL_IP: keycloak-2
    volumes:
      - ./config/realms:/opt/keycloak/data/import
    command: 
      - "start-dev"
      - "--import-realm"
    ports:
      - "${KEYCLOAK_2_PORT}:8080"
    networks:
      - auth-network
  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:7.5
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ${DATA_DIR}/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge